= GlassUI

Note: Deep in development, not ready for use yet.

GlassUI basically tries to reproduce the look of the https://hyprland.org/hall_of_fame/[hot linux setups] that you see every now and then on Windows(only latest will be actively supported).

== Roadmap (sorted by priority and feasibility):
- [ ] Replacing the taskbar (and add a lot more features)
- [ ] Making window transparency settable
- [ ] Creating custom desktop backgrounds
- [.line-through]#Creating a Minecraft-like resource pack manager which can replace the frontend# (Impossible because of change from tauri to native rendering, afaik)
- [ ] Add optional screen effects (for example a beating depending on the music)
- [ ] Replacing the start and search menu
- [ ] Replacing the file explorer
- [ ] Replacing the tab switching menu
- [ ] Replacing the text editor
- [ ] Creating a twm
- [ ] Replacing the cursor
- [ ] Replacing the default window decoration

== Developing
For the UI library, see https://github.com/Xyndra/xyndra_winui[this repo].
Note that the other library is supposed to be generic, so only actual UI library features should be added there.

== Reasons for past decisions
- Change from Tauri to Skia: Tauri lagging way too much to create 4 windows that
    are always active
- Change from Skia to my own library:
    . Compiling the Skia dependency took 18 minutes
    . Skia took 3% GPU for a single window, so it was scrapped for performance reasons
- Making the UI library separate to the main library:
    . I want to have a UI library that looks good while not eating all resources
    . There should not be flowing boundaries between rendering and logic to
        avoid bugs and make it easier to maintain
